### ISSUE TITLE
Failed at cmake ..

### ISSUE THREAD

**Issue by anistark** [fabianishere/brainfuck#37]
Faced this issue while installing brainfuck in ubuntu x86_64 at this step

```
cmake ..
```
 
Output :

```
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Error at CMakeLists.txt:29 (message):
  Doxygen is needed to build the documentation.
```

**Comment by fabianishere** [comment]
Doxygen is required when building the documentation. To disable documentation, run cmake with the following option:
```sh
$  cmake -DWITH_DOCUMENTATION=FALSE ..
```

This option is enabled by default on the `develop` branch. Also, since this is the `develop` branch, the interpreter won't work as expected. If you are looking for a working interpreter, take a look the master branch: https://github.com/fabianishere/brainfuck.

Thank you!
